name: test Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: sh check
        run: find . -name "*sh" -exec bash -n {} \;

      - name: Say hello
        run: echo "Hello from GitHub Actions"

      - name: Show date
        run: date

      - name: secret check
        run: echo $MY_SECRET
